#+TITLE: Modelling Semantic Relations with Distributional Semantics and Deep Learning: Question Answering, Entailment Recognition and Paraphrase Detection

* Prerequisites
1. Download the source code: http://nlx-server.di.fc.ul.pt/dissertations/Maraev/msrdsdl.tar.gz (username and password are provided upon request).
2. Extract the code:
   #+BEGIN_SRC sh
     tar -xvf msrdsl.tar.gz
     cd msrdsdl
   #+END_SRC
3. You will need *Python version 3.4.3 or higher*.
4. Install required packages:
   #+BEGIN_SRC sh :exports code
     pip install -r requirements.txt
   #+END_SRC
5. Set up Theano backend for Keras by editing the configuration file =~/.keras/keras.json= and changing the field =backend= to ="theano"=.
6. If you want to run experiments that require word embeddings you need to download and extract distributional models:
   #+BEGIN_SRC sh :exports code
     wget http://nlx-server.di.fc.ul.pt/dissertations/Maraev/models.tar.gz
     tar -xvf models.tar.gz
   #+END_SRC

* About the program
After satisfying all the prerequisites you will have the following directory structure: 
#+BEGIN_SRC 
|-- cnn.py
|-- data
|   |-- askubuntu
|   |   |-- clue
|   |   |   |-- test.tsv
|   |   |   |-- train.tsv
|   |   |   '-- val.tsv
|   |   '-- noclue
|   |       |-- test.tsv
|   |       |-- train.tsv
|   |       '-- val.tsv
|   |-- meta
|   |   |-- clue
|   |   |   |-- test.tsv
|   |   |   |-- train.tsv
|   |   |   '-- val.tsv
|   |   '-- noclue
|   |       |-- test.tsv
|   |       |-- train.tsv
|   |       '-- val.tsv
|   |-- pt
|   |   |-- test.csv
|   |   |-- test.tsv
|   |   |-- test.tsv~
|   |   |-- train.csv
|   |   |-- train.tsv
|   |   '-- train.tsv~
|   '-- ru
|       |-- test.tsv
|       '-- train.tsv
|-- __init.py__
|-- models
|   |-- askubuntu.w2v
|   |-- meta.w2v
|   |-- pt.w2v
|   |-- pt.w2v.min.cache.npy
|   '-- ruscorpora.model.w2v
|-- preprocess.py
|-- README.org
'-- requirements.txt
#+END_SRC

You can run the application =./cnn.py= with the =--help= argument to see available parameters.

To change hyperparameters you can modify the method =SentenceSimilarity. set_hyperparameters= by adding new modes. 

* Replication of my work
** Question Answering
*** Replication of the work by Bogdanova et al. (2015)
    For AskUbuntu dataset:
    #+BEGIN_SRC sh :exports code
      ./cnn.py replication --train data/askubuntu/clue/train.tsv \
               --val data/askubuntu/clue/val.tsv \
               --test data/askubuntu/clue/test.tsv \
               --w2v models/askubuntu.w2v
    #+END_SRC
    For META Stackexchange dataset:
    #+BEGIN_SRC sh :exports code
      ./cnn.py replication --train data/meta/clue/train.tsv \
               --val data/meta/clue/val.tsv \
               --test data/meta/clue/test.tsv \
               --w2v models/meta.w2v
    #+END_SRC

*** Impact of text preprocessing (clue phrases removed)
    For AskUbuntu dataset:
    #+BEGIN_SRC sh :exports code
      ./cnn.py pp_impact --train data/askubuntu/noclue/train.tsv \
               --val data/askubuntu/noclue/val.tsv \
               --test data/askubuntu/noclue/test.tsv \
               --w2v models/askubuntu.w2v
    #+END_SRC
    For META Stackexchange dataset:    
    #+BEGIN_SRC sh :exports code
      ./cnn.py pp_impact --train data/meta/noclue/train.tsv \
               --val data/meta/noclue/val.tsv \
               --test data/meta/noclue/test.tsv \
               --w2v models/meta.w2v
    #+END_SRC

*** Impact of word embeddings (no pre-trained word embeddings)
    #+BEGIN_SRC sh :exports code
      ./cnn.py we_impact --train data/askubuntu/noclue/train.tsv \
               --val data/askubuntu/noclue/val.tsv \
               --test data/askubuntu/noclue/test.tsv
    #+END_SRC

** Portuguese Entailment Recognition
*** Run 1
    #+BEGIN_SRC sh :exports code
      ./cnn.py pt_1 --train data/pt/train.tsv \
               --val data/pt/test.tsv \
               --w2v models/pt.w2v
    #+END_SRC

*** Run 2
    #+BEGIN_SRC sh :exports code
      ./cnn.py pt_2 --train data/pt/train.tsv --val data/pt/test.tsv
    #+END_SRC

** Russian Paraphrase Detection
*** Non-standard run 
    #+BEGIN_SRC sh :exports code
      ./cnn.py ru_ns --train data/ru/train.tsv \
               --val data/ru/test.tsv \
               --w2v models/ruscorpora.model.w2v
    #+END_SRC

*** Standard run
**** Word embeddings
    #+BEGIN_SRC sh :exports code
      ./cnn.py ru_word --train data/ru/train.tsv --val data/ru/test.tsv
    #+END_SRC

**** Character embeddings
    #+BEGIN_SRC sh :exports code
      ./cnn.py ru_char --train data/ru/train.tsv --val data/ru/test.tsv
    #+END_SRC
